# Generated by Django 2.1.5 on 2019-01-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={},
        ),
    ]
