# Generated by Django 2.1.5 on 2019-01-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareData', '0002_auto_20190108_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
