# Generated by Django 2.1.3 on 2018-11-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivation',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
