# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-15 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working', models.BooleanField()),
                ('command', models.TextField()),
                ('command2', models.TextField(blank=True)),
                ('success', models.IntegerField(blank=True, default=0)),
                ('verified', models.BooleanField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('fails', models.IntegerField(blank=True, default=0)),
                ('downloads', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ErrorComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_comment', models.TextField(blank=True)),
                ('error', models.TextField()),
                ('offical', models.BooleanField(default=False)),
                ('Spam', models.BooleanField(default=False)),
                ('helpfull', models.BooleanField(default=False)),
                ('unHelpfull', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Linux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OsName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OsVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Osversion', models.CharField(max_length=250)),
                ('OsName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platforms.Linux')),
            ],
        ),
        migrations.CreateModel(
            name='PackageManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('downloads', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='linux',
            name='BaseDistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platforms.PackageManager'),
        ),
        migrations.AddField(
            model_name='errorcomment',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platforms.Linux'),
        ),
        migrations.AddField(
            model_name='errorcomment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Platforms.ErrorComment'),
        ),
        migrations.AddField(
            model_name='errorcomment',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='_errorcomment_reply_+', to='Platforms.ErrorComment'),
        ),
    ]
