# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-15 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SoftwareData', '0001_initial'),
        ('Platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcomment',
            name='software',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SoftwareData.Software'),
        ),
        migrations.AddField(
            model_name='errorcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='error',
            name='BaseDistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='Platforms.OsVersion'),
        ),
        migrations.AddField(
            model_name='command',
            name='OsVersion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platforms.OsVersion'),
        ),
        migrations.AddField(
            model_name='command',
            name='PackageManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platforms.PackageManager'),
        ),
    ]
