# Generated by Django 2.1.5 on 2019-01-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platforms', '0002_auto_20180715_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='working',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='errorcomment',
            name='Spam',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='errorcomment',
            name='helpfull',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='errorcomment',
            name='unHelpfull',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
